### ISSUE TITLE
[Bug]: VT ArmorStatutes Compact not working, Crash on client

### ISSUE THREAD

**Issue by Shibva** [Fuzss/armorstatues#34]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.19.2

### Mod Version(s) (Required)

4.0.8

### Minimal Setup (Required)

No

### Notes (Required)

Unable to test for Minimal setup due to uniqueness of issue

This is somewhat in relation with #32 as he and I are on mutual servers. Not sure why he is having issues though as he is likey using the same pack and I managed to get though boot; odd.

Anyhow besides the point, the issue here is that I crash when trying to interact with the armor stand. The mod is NOT present on the server, but the Vanilla Tweaks Datapack that the mod advertises it having serverside compact for is present; hence why I am unable to verity if this is a minimal setup reproducible. For best Results in the case that this needs to be a 1:1 case, please use the pack https://www.curseforge.com/minecraft/modpacks/create-technical-4 and add the VT addon into a dedicated environment and a client with the mod in question.

### latest.log (Required)

https://gist.github.com/Shibva/a626c5b84a03f4cba4a2470a306e1c08

**Comment by Shibva** [comment]
what the hell? why did it make two?

**Comment by Eatham532** [comment]
I am also having my game crash 1.21.1 using the VT mode. Executing specific VT commands or moving to a specific tab (position tab is affected) cause it to crash.

Here is the error for navigating to the position tab.
```
[09:16:53] [Render thread/ERROR]:
Reported exception thrown!
net.minecraft.class_148: Rendering screen
at net.minecraft.class_757.method_3192(class_757.java:922) ~[client-intermediary.jar:?]
at net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void fuzs.puzzleslib.api.client.gui.v2.components.GuiGraphicsHelper.blitNineSliced(net.minecraft.class_332, net.minecraft.class_2960, int, int, int, int, int, int, int, int, int, int)'
at fuzs.statuemenus.api.v1.client.gui.components.NewTextureSliderButton.method_48579(NewTextureSliderButton.java:46) ~[statuemenus-21.1.0-5e7f64aee34627c0.jar:?]
at fuzs.statuemenus.api.v1.client.gui.screens.ArmorStandPositionScreen$RotationWidget$1.method_48579(ArmorStandPositionScreen.java:152) ~[statuemenus-21.1.0-5e7f64aee34627c0.jar:?]
at net.minecraft.class_339.method_25394(class_339.java:66) ~[client-intermediary.jar:?]
at net.minecraft.class_437.method_25394(class_437.java:128) ~[client-intermediary.jar:?]
at fuzs.statuemenus.api.v1.client.gui.screens.AbstractArmorStandScreen.method_25394(AbstractArmorStandScreen.java:182) ~[statuemenus-21.1.0-5e7f64aee34627c0.jar:?]
at net.minecraft.class_437.method_47413(class_437.java:117) ~[client-intermediary.jar:?]
at net.minecraft.class_757.mixinextras$bridge$method_47413$258(class_757.java) ~[client-intermediary.jar:?]
at net.minecraft.class_757.wrapOperation$bka000$fabric-screen-api-v1$onRenderScreen(class_757.java:3586) ~[client-intermediary.jar:?]
at net.minecraft.class_757.method_3192(class_757.java:913) ~[client-intermediary.jar:?]
... 6 more
```
